### ISSUE TITLE
News display 404

### ISSUE THREAD

**Issue by SteffenL** [SteffenL/dise#1]
The web view on the first screen in the app displays HTTP 404. This is because the web service is no longer operational.

Ideas for a fix:

- Only display news if any were returned by the server.
- Remove the news view and do not deal with it.

**Comment by JjTheHusky** [comment]
Perhaps a simple HTML page can be used instead? I'm not sure what was displayed before it stopped working.

**Comment by SteffenL** [comment]
Before it stopped working, the news window displayed a list of recent releases or blog posts. I do not quite remember whether it was based on a simple HTML document generated from the blog feed or the actual releases in a database, but I think it was the former. To be frank, I think the usefulness of the whole thing is questionable.

**Comment by SteffenL** [comment]
The web view for the news has been removed. I may add something similar back again later but it will likely not be a web view.
