### ISSUE TITLE
Fury lasts forever

### ISSUE THREAD

**Issue by JjTheHusky** [SteffenL/dise#10]
Fury seems to last forever with certain tweaks enabled. Currently going through to see which ones it may be, and will update thread.

**Comment by Wahkah** [comment]
Did you enable godmode with fury? It could be an old way of doing godmode.

**Comment by JjTheHusky** [comment]
This is tested in DE, this may not be an issue for the original game.
Having `Instant Fury` on will make fury last forever, the user will have to reload the last checkpoint to stop it.
In addition, `Fury lasts longer` does not work.

**Comment by Wahkah** [comment]
Maybe this is a proc with the QNaN, Steffen?

**Comment by JjTheHusky** [comment]
After reviewing this again, this is mainly just an issue with the game and not with DISE. It may help to review the tweaks for DE's to see if anything has changed from the previous versions.
Closing
