### ISSUE TITLE
Backup Limit reached

### ISSUE THREAD

**Issue by JjTheHusky** [SteffenL/dise#11]
Small bug; Backup limit reached window is too small to display all text, and window cannot be resized.

![image](https://user-images.githubusercontent.com/25309518/58437408-6f730b80-808f-11e9-8a9e-939aa616d527.png)

**Comment by Wahkah** [comment]
Is this after the save has been backed up/modified a few times? I havent had a chance to test yet.

**Comment by JjTheHusky** [comment]
> Is this after the save has been backed up/modified a few times? I havent had a chance to test yet.

This window shows up before the file is saved and Steam syncs, if that's what you're talking about.

**Comment by SteffenL** [comment]
That's a good find! Thanks!

**Comment by SteffenL** [comment]
Fixed by resizing the window to fit its content.

![image](https://user-images.githubusercontent.com/1543854/58467769-8de31080-813c-11e9-91cf-173912c4f168.png)
