### ISSUE TITLE
Website should work over HTTPS

### ISSUE THREAD

**Issue by SteffenL** [SteffenL/dise#13]
I am not sure if the website ever worked over HTTPS but it's something to look into.

Works:
http://deadislandsaveeditor.steffenl.com/

Does not work:
https://deadislandsaveeditor.steffenl.com/

**Comment by JjTheHusky** [comment]
I'm not exactly sure what kind of system you are running for your site, but LetsEncrypt may be useful and its free, just requires some manual verification and time. Cloudflare is also another option, and provides free SSL and website protection (DDoS), and has a free plan.

**Comment by SteffenL** [comment]
Thank you!

The site is hosted on blogger.com. I signed in there now and found this piece of news right in front of me!

> HTTPS for custom domains is now available on your blog

Sounds precisely like what we need!

**Comment by JjTheHusky** [comment]
Sounds good! Don't forget your other subdomains :P

**Comment by SteffenL** [comment]
HTTPS works after switching it on. 😄 Certificate issued by Let's Encrypt!
