### ISSUE TITLE
Add GH wiki/pages space

### ISSUE THREAD

**Issue by SteffenL** [SteffenL/dise#14]
https://steffenl.github.io/dise/

Add content to `docs` directory on master branch.

**Comment by JjTheHusky** [comment]
I will try to contribute! I haven't used github pages before so I will have to learn lol

**Comment by SteffenL** [comment]
I just added one dummy file for now but it requires more setup than this to be useful.

**Comment by JjTheHusky** [comment]
Should it be in this markdown format, or is html ok?

**Comment by SteffenL** [comment]
HTML is fine for templating. One can place HTML inside Markdown too. Right now, I do not have a plan for how it should work. I'm thinking that each page should be a separate file (whether it's Markdown or something else) without having to duplicate the same HTML code for each page.

**Comment by JjTheHusky** [comment]
Wiki is currently being worked on and will have a few pages available, then we can go from there.

**Comment by JjTheHusky** [comment]
Well I never got around to messing with this :P 

Instead of using Github pages, what if the wiki is hosting alongside the DISE website?

**Comment by SteffenL** [comment]
After all I think it's better that we don't lock ourselves into using GitHub Pages. The wiki can be hosted elsewhere you suggested.
