### ISSUE TITLE
Profile editor for Definitive Edition

### ISSUE THREAD

**Issue by SteffenL** [SteffenL/dise#15]
I have not tested the current profile editing features with Definitive Edition. The new advanced editor works for the original games but not Definitive Edition (the list of fields is empty).

**Comment by JjTheHusky** [comment]
What is a profile editor? I saw 'profiles' in the editor but I don't quite understand what it is

**Comment by SteffenL** [comment]
For example, the "profile" contains information about chapters that have been completed and allows starting a new game from a given chapter. It also contains some statistics, challenge/achievement progress, etc. It has other info that looks as if they have something to do with in-game options/settings but I have not seen that it actually stays in sync with the actual options.

**Comment by Wahkah** [comment]
Some of the variables don’t sync up. An example is forcedamagetype since it changes every new game state. I can prolly find that list and awnd it if u wanna weed thru the toggleables from the sticky settings

**Comment by SteffenL** [comment]
DE profiles are compressed with gzip and DISE appears to be able to read them as long as they are decompressed first.

**Comment by SteffenL** [comment]
DISE now supports profiles for Definitive Edition but there is one potential problem because game detection for profiles is based on the file name.

| Detection            | Game  |
| -------------------- | ----- |
| Uncompressed `*.pro` | DI    |
| Compressed `*.pro`   | DIDE  |
| `*.prr`              | DIR   |
| `*.pro.riptide`      | DIRDE |

So if you have a `*.prr` file inside the DIDE/DIRDE folder then DISE syncs that file for DIR instead of DIRDE.

If this turns out to be a problem then I will have to fix it somehow. Otherwise, I will just leave it alone for now because it will take more effort to change the detection method.
