### ISSUE TITLE
Game logo's cover save text with default window size

### ISSUE THREAD

**Issue by JjTheHusky** [SteffenL/dise#19]
When launching DISE at the default window size, the game logo's can cover the game text, usually just the level number.

DISE Will remember the window size and position on each launch, so this is only an issue on the first launch until the user changes it.

![dise_2ZfEG2rVDN](https://user-images.githubusercontent.com/25309518/59120221-7cf38580-891a-11e9-864f-6a38f9e5afa8.png)

**Comment by SteffenL** [comment]
Thank you! I think there is a need to redesign the list of profiles to waste less space. Also the news area is not doing anything useful right now.

**Comment by SteffenL** [comment]
The list of saved games and profiles have now been merged to waste less space. The same default window size is large enough to not overlap anything with this change.

![image](https://user-images.githubusercontent.com/1543854/59133408-32a0f180-8978-11e9-943a-b7d56f3a943f.png)
