### ISSUE TITLE
Map and Skills not showing for Ryder

### ISSUE THREAD

**Issue by JjTheHusky** [SteffenL/dise#22]
Icons for the Skills tab do not show for Ryder.
![image](https://user-images.githubusercontent.com/25309518/59175335-c4e0fb00-8b1a-11e9-881e-f3f5c66f6f57.png)

And the map does not show for Ryder's campaign. Unsure if it exists or how many maps there are.
![image](https://user-images.githubusercontent.com/25309518/59175361-e6da7d80-8b1a-11e9-9103-d194389d7173.png)

**Comment by SteffenL** [comment]
Thanks. Last time I checked, there were no skill icons, skill text or even maps available for Ryder.

**Comment by JjTheHusky** [comment]
Whoops, it was 2 am and I totally forgot that skills did not exist in game for Ryder.
