### ISSUE TITLE
Saving DE results in error

### ISSUE THREAD

**Issue by JjTheHusky** [SteffenL/dise#8]
>Error while syncing. Message: The file does not appear to be in your Steam account's game storage folder.

This may be related to #7, I also notice that it opens the original dead island game to sync with steam, instead of DE.

The file is actually saved, and changes are reflected in game. Unsure if it actually syncs with the cloud in the editor or when the game launches.

**Comment by SteffenL** [comment]
Can you please try to set the correct "game storage location" (and app IDs) in the preferences dialog in DISE and see if the problem persists? I suspect that DISE may detect that the save is in an unexpected location because of that.

**Comment by JjTheHusky** [comment]
This fixes the issue, using the ID's from #7.

**Comment by SteffenL** [comment]
The work done for #7 fixes this.
